# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_ROCKCHIP) += \
	orangepi-5-i2c1-m2.dtbo \
	orangepi-5-i2c1-m4.dtbo \
	orangepi-5-i2c2-m0.dtbo \
	orangepi-5-i2c2-m4.dtbo \
	orangepi-5-i2c3-m0.dtbo \
	orangepi-5-i2c4-m3.dtbo \
	orangepi-5-i2c5-m3.dtbo \
	orangepi-5-i2c6-m4.dtbo \
	orangepi-5-i2c8-m2.dtbo \
	orangepi-5-pwm0-m0.dtbo \
	orangepi-5-pwm0-m1.dtbo \
	orangepi-5-pwm0-m2.dtbo \
	orangepi-5-pwm1-m0.dtbo \
	orangepi-5-pwm1-m1.dtbo \
	orangepi-5-pwm1-m2.dtbo \
	orangepi-5-pwm3-m0.dtbo \
	orangepi-5-pwm3-m2.dtbo \
	orangepi-5-pwm3-m3.dtbo \
	orangepi-5-pwm10-m0.dtbo \
	orangepi-5-pwm11-m0.dtbo \
	orangepi-5-pwm12-m0.dtbo \
	orangepi-5-pwm13-m0.dtbo \
	orangepi-5-pwm13-m2.dtbo \
	orangepi-5-pwm14-m0.dtbo \
	orangepi-5-pwm14-m1.dtbo \
	orangepi-5-pwm14-m2.dtbo \
	orangepi-5-pwm15-m1.dtbo \
	orangepi-5-pwm15-m2.dtbo \
	orangepi-5-uart0-m2.dtbo \
	orangepi-5-uart1-m1.dtbo \
	orangepi-5-uart3-m0.dtbo \
	orangepi-5-uart3-m1.dtbo \
	orangepi-5-uart4-m0.dtbo \
	orangepi-5-uart4-m2.dtbo \
	orangepi-5-uart6-m1.dtbo \
	orangepi-5-uart7-m2.dtbo \
	orangepi-5-uart8-m1.dtbo \
	orangepi-5-can0-m0.dtbo \
	orangepi-5-can1-m0.dtbo \
	orangepi-5-can1-m1.dtbo \
	orangepi-5-can2-m1.dtbo \
	orangepi-5-lcd1.dtbo \
	orangepi-5-lcd2.dtbo \
	orangepi-5-plus-lcd.dtbo \
	orangepi-5-ov13850-c1.dtbo \
	orangepi-5-ov13850-c2.dtbo \
	orangepi-5-ov13850-c3.dtbo \
	orangepi-5-ov13855-c1.dtbo \
	orangepi-5-ov13855-c2.dtbo \
	orangepi-5-ov13855-c3.dtbo \
	orangepi-5-plus-ov13850.dtbo \
	orangepi-5-plus-ov13855.dtbo \
	orangepi-5-dmc.dtbo \
	orangepi-5-sata.dtbo \
	orangepi-5-sata2.dtbo \
	orangepi-5-hdmirx.dtbo \
	orangepi-5-hdmi2-8k.dtbo \
	orangepi-5-wifi-ap6275p.dtbo \
	orangepi-5-wifi-pcie.dtbo \
	orangepi-5-spi0-m2-cs0-spidev.dtbo \
	orangepi-5-spi0-m2-cs1-spidev.dtbo \
	orangepi-5-spi0-m2-cs0-cs1-spidev.dtbo \
	orangepi-5-spi4-m0-cs1-spidev.dtbo \
	orangepi-5-spi4-m1-cs0-spidev.dtbo \
	orangepi-5-spi4-m1-cs1-spidev.dtbo \
	orangepi-5-spi4-m1-cs0-cs1-spidev.dtbo \
	orangepi-5-spi4-m2-cs0-spidev.dtbo \
	rock-5a-hdmi-8k.dtbo \
	rock-5a-i2c5-rtc-hym8563.dtbo \
	rock-5a-radxa-camera-4k.dtbo \
	rock-5a-radxa-display-10hd.dtbo \
	rock-5a-radxa-display-8hd.dtbo \
	rock-5a-spi-nor-flash.dtbo \
	rock-5a-usb-otg.dtbo \
	rock-5b-hdmi1-8k.dtbo \
	rock-5b-hdmi2-8k.dtbo \
	rock-5b-pd-max-voltage-12v.dtbo \
	rock-5b-radxa-display-10hd.dtbo \
	rock-5b-radxa-display-8hd.dtbo \
	rock-5b-rpi-camera-v2.dtbo \
	rock-5b-radxa-camera-4k.dtbo \
	rock-5b-sata.dtbo \
	rockchip-rk3588-opp-oc-24ghz.dtbo

targets += $(dtbo-y) $(dtbotxt-y)

always-y		:= $(dtbo-y) $(dtbotxt-y)
clean-files		:= *.dtbo

